openapi: '3.0.0'
info:
  version: 1.0.0
  title: Marain User Notifications API Delivery Channel
servers:
  - url: http://localhost:7081/
paths:
  /{tenantId}/marain/users/{userId}/notifications:
    get:
      summary: Get all notifications for a user
      operationId: getNotificationsForUser
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/userId'
        - $ref: '#/components/parameters/sinceNotificationId'
        - $ref: '#/components/parameters/maxItems'
        - $ref: '#/components/parameters/continuationToken'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedNotificationsListResponse'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /{tenantId}/marain/usernotifications/{notificationId}:
    get:
      summary: Gets a single notification
      operationId: getNotification
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/notificationId'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notification'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

  /{tenantId}/marain/usernotifications/{notificationId}/read:
    post:
      summary: Mark the specified notification as read
      operationId: markNotificationRead
      parameters:
        - $ref: '#/components/parameters/tenantId'
        - $ref: '#/components/parameters/notificationId'
      responses:
        '202':
          description: Accepted
          headers:
            Location:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not found
        '403':
          description: Forbidden
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'

components:
  schemas:
    Notification:
      description: A single notification for a specific user.
      anyOf:
      - $ref: '#/components/schemas/Resource'
      - type: object
        properties:
          contentType:
            type: string
            description: The content type of the response
          notificationType:
            type: string
            description: The type of the notification.
            nullable: false
          properties:
            $ref: '#/components/schemas/PropertyBag'
          userId:
            type: string
          timestamp:
            type: string
            format: date-time
            description: The date and time at which the event being notified took place.
          delivered:
            description: A boolean indicating whether or not the notification has been delivered via at least one channel.
            type: boolean
          read:
            description: A boolean indicating whether or not the notification has been read/acknowledged via at least one channel.
            type: boolean
          _links:
            type: object
            properties:
              self:
                $ref: '#/components/schemas/Link'
              mark-read:
                $ref: '#/components/schemas/Link'

    PagedNotificationsListResponse:
      description: A paged list of notifications
      anyOf:
      - $ref: '#/components/schemas/PagedListResource'
      - type: object
        properties:
          _embedded:
            type: object
            properties:
              items:
                oneOf:
                - $ref: '#/components/schemas/Notification'
                - type: array
                  items:
                    $ref: '#/components/schemas/Notification'

    CorrelationIds:
      description: A list of Ids that can be used to correlate log entries. 
      type: array
      items:
        type: string

    Link:
      type: object
      required:
        - href
      properties:
        href:
          type: string
          title: URI of the target resource
          description: Either a URI [RFC3986] or URI Template [RFC6570] of the target
            resource.
        templated:
          type: boolean
          default: false
          title: URI Template
          description: Is true when the link object's href property is a URI Template.
            Defaults to false.
        type:
          type: string
          pattern: "^(application|audio|example|image|message|model|multipart|text|video)\\/[a-zA-Z0-9!#\\$&\\.\\+-\\^_]{1,127}$"
          title: Media type indication of the target resource
          description: When present, used as a hint to indicate the media type expected
            when dereferencing the target resource.
        name:
          type: string
          title: Secondary key
          description: When present, may be used as a secondary key for selecting
            link objects that contain the same relation type.
        profile:
          type: string
          format: uri
          title: Additional semantics of the target resource
          description: A URI that, when dereferenced, results in a profile to allow
            clients to learn about additional semantics (constraints, conventions,
            extensions) that are associated with the target resource representation,
            in addition to those defined by the HAL media type and relations.
        title:
          type: string
          title: Human-readable identifier
          description: When present, is used to label the destination of a link
            such that it can be used as a human-readable identifier (e.g. a menu
            entry) in the language indicated by the Content-Language header (if
            present).
        hreflang:
          type: string
          pattern: "^([a-zA-Z]{2,3}(-[a-zA-Z]{3}(-[a-zA-Z]{3}){0,2})?(-[a-zA-Z]{4})?(-([a-zA-Z]{2}|[0-9]{3}))?(-([a-zA-Z0-9]{5,8}|[0-9][a-zA-Z0-9]{3}))*([0-9A-WY-Za-wy-z](-[a-zA-Z0-9]{2,8}){1,})*(x-[a-zA-Z0-9]{2,8})?)|(x-[a-zA-Z0-9]{2,8})|(en-GB-oed)|(i-ami)|(i-bnn)|(i-default)|(i-enochian)|(i-hak)|(i-klingon)|(i-lux)|(i-mingo)|(i-navajo)|(i-pwn)|(i-tao)|(i-tay)|(i-tsu)|(sgn-BE-FR)|(sgn-BE-NL)|(sgn-CH-DE)|(art-lojban)|(cel-gaulish)|(no-bok)|(no-nyn)|(zh-guoyu)|(zh-hakka)|(zh-min)|(zh-min-nan)|(zh-xiang)$"
          title: Language indication of the target resource [RFC5988]
          description: When present, is a hint in RFC5646 format indicating what
            the language of the result of dereferencing the link should be.  Note
            that this is only a hint; for example, it does not override the Content-Language
            header of a HTTP response obtained by actually following the link.

    LinkCollection:
      description: a collection of links
      type: array
      items:
        $ref: '#/components/schemas/Link'

    PropertyBag:
      type: object
      additionalProperties: true
      uniqueItems: true

    ResourceCollection:
      description: a collection of resources
      type: array
      items:
        $ref: '#/components/schemas/Resource'

    Resource:
      type: object
      properties:
        _links:
          type: object
          title: Hyperlink
          description: Represents a hyperlink from the cotntaining resource to a URI.
          additionalProperties:
            oneOf:
            - $ref: '#/components/schemas/Link'
            - type: array
              items:
                $ref: '#/components/schemas/Link'
              uniqueItems: true
              additionalProperties: false
        _embedded:
          type: object
          additionalProperties:
            oneOf:
            - $ref: '#/components/schemas/Resource'
            - type: array
              items:
                $ref: '#/components/schemas/Resource'
              uniqueItems: true
              additionalProperties: false
      additionalProperties: true

    PagedListResource:
      description: A resource representation of a paged list
      anyOf:
        - $ref: '#/components/schemas/Resource'
        - type: object
          required:
          - _links
          properties:
            contentType:
              type: string
              description: The content type of the response
            _links:
              type: object
              title: Hyperlinks
              description: Represents a hyperlink from the containing resource to a URI.
              properties:
                items:
                  anyOf:
                    - $ref: '#/components/schemas/Link'
                    - $ref: '#/components/schemas/LinkCollection'
                next:
                  $ref: '#/components/schemas/Link'
                prev:
                  $ref: '#/components/schemas/Link'
              additionalProperties:
                anyOf:
                  - $ref: '#/components/schemas/Link'
                  - $ref: '#/components/schemas/LinkCollection'
                uniqueItems: true
          additionalProperties: true

    ProblemDetails:
      required:
        - status
        - detail
      properties:
        status:
          type: integer
          format: int32
        detail:
          type: string
        title:
          type: string
        instance:
          type: string
          format: url
        type: 
          type: string
          format: url
        validationErrors: 
          type: array
      additionalProperties: true

  parameters:
    tenantId:
      name: tenantId
      in: path
      x-ms-parameter-location: method
      description: The tenant within which the request should operate
      required: true
      schema:
        type: string
    userId:
      name: userId
      in: path
      x-ms-parameter-location: method
      description: The Id of the user for whom data is being operated on
      required: true
      schema:
        type: string
    notificationId:
      name: notificationId
      in: path
      x-ms-parameter-location: method
      description: The Id of the notification being updated
      required: true
      schema:
        type: string
    sinceNotificationId:
      name: sinceNotificationId
      in: query
      x-ms-parameter-location: method
      description: When retrieving notifications, all returned notifications should have a greater sequence number than the supplied value
      required: false
      schema:
        type: string
    continuationToken:
      name: continuationToken
      in: query
      x-ms-parameter-location: method
      description: A continuation token for an operation where more data is available. If continuation token is specified, other query parameters are ignored.
      required: false
      schema:
        type: string
    maxItems:
      name: maxItems
      in: query
      x-ms-parameter-location: method
      description: The maximum number of items to return in the request. Fewer than this number may be returned.
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 50
